### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by kaspergrubbe** [luckymarmot/Paw-HARImporter#2]
I have just installed the plugin, and I have a hard time figuring out where to paste my HAR-request.

**Comment by mittsh** [comment]
In the File menu, pick Import.

![image](https://cloud.githubusercontent.com/assets/1319906/7891641/914d6828-064e-11e5-84df-b4238ce205e6.png)

Hope it helps!

**Comment by jeroenvisser101** [comment]
It's important to note that HAR files from chrome are just JSON files. Open a new text file, paste the JSON, save them, and open them with Paw. We'll change this when Paw accepts pasting as an import, or just string inputs!

**Comment by mittsh** [comment]
@jeroenvisser101 :+1: absolutely!

**Comment by kaspergrubbe** [comment]
Thanks!
