### ISSUE TITLE
Import fails with 'Invalid UTF-8 detected'

### ISSUE THREAD

**Issue by andreionut** [luckymarmot/Paw-HARImporter#7]
I received a HAR file to investigate and I could not open it with Paw. I managed to replicate the issue by browsing the [paw.cloud](https://paw.cloud) site, saving it as a HAR and I got the same error.

The extension console shows this: 
`JS Exception Line 2635. Error: Invalid UTF-8 detected`

![screen shot 2018-04-02 at 11 50 43](https://user-images.githubusercontent.com/1051275/38193844-181a50e6-366c-11e8-8d56-a8ef0ae74697.png)

I've uploaded the HAR file: https://cl.ly/3t1a3k0z0O3d

The file can be opened with Charles, the Chrome extension Has Viewer and Sublime Text 3.

Paw Details:
Version 3.1.5 (Retail)
Build D09956 (3001005003) | Document Model AFD743

**Comment by KeyZer** [comment]
I have the same issue, any updates on this?

**Comment by ileacristian** [comment]
Same issue here

**Comment by JobsIsMyHomeboy** [comment]
I had the same problem. Export the request from Charles as a .har file and it works great. To do that just select export in Charles like normal, but change the format to "HTTP Archive (.har)". Then import to PAW.

**Comment by afturner** [comment]
It appears that binary data (like images, audio, etc.) will break the import. Importing in Charles, selecting requests you want and exporting as HAR (avoiding binary data) seems to work for me.
